apiVersion: cve-release.skynetx.me/v1
kind: GitHubReleasesMonitor
metadata:
  labels:
    app.kubernetes.io/name: cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubreleasesmonitor-sample
spec:
  url: "https://github.com/CVEProject/cvelistV5/archive/refs/heads/main.zip"
  monitorfrom: "now"
